# Generated by Django 5.1.1 on 2025-02-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_newsletter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetter',
            new_name='AdsLetter',
        ),
    ]
