# Generated by Django 5.1.1 on 2025-02-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='ad',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='video1',
            field=models.FileField(blank=True, null=True, upload_to='ads_videos/'),
        ),
        migrations.AddField(
            model_name='ad',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='ads_videos/'),
        ),
    ]
